### ISSUE TITLE
ntlmrelayx output

### ISSUE THREAD

**Issue by alghammariosmah** [dirkjanm/PrivExchange#14]
A quick question, so I tested my local network exchange server using ntlmrelayx and privexchange.py, and I had two results: 
The first one I got rpc_s_access_denied, which I don't know if my local exchange server is secured or not:
[*] Authenticating against smb://DomainController1 as Local\CSXCH01$ SUCCEED
[-] DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied

The second:
[-] Negotiating NTLM with smb://DomainController2 failed. Skipping to next target
[*] HTTPD: Received connection from xxx.xxx.xxx.xx, attacking target smb://DomainController2
[*] HTTPD: Client requested path: /c7onjkvrkg
[-] SMBCLient error: Connection was reset. Possibly the target has SMBv1 disabled. Try running ntlmrelayx with -smb2support

**Comment by dirkjanm** [comment]
You're relaying the authentication to SMB in both examples. The default is that ntlmrelayx tries to dump the local machine hashes when this happens, which requires administrative privileges on the domain controller. Exchange does not have these privileges, which is why the attack fails (the access denied message). You should relay to LDAP, on which Exchange does have high permissions if it is vulnerable.
Also normally relaying to SMB on a domain controller won't work due to signing, but it seems that is not enforced on the DC you are targeting.
