### ISSUE TITLE
About your blog post regarding this exploit

### ISSUE THREAD

**Issue by JulioQc** [dirkjanm/PrivExchange#15]
I tried your recommended fix and those broke Exchange in a terrible way:
- Enabling FE extended protection (with or without kernel mode) with break authentication
- Removing the DisableLoopbackCheck will also break authentication

This when authentication is done behind a L7 load-balancer! I suggest this be clarified before other break their exchange. Doesn't seem to be a problem with a single exchange server.

**Comment by dirkjanm** [comment]
Thanks for your feedback. It is always recommended that people test changes to see if they break something. In this case it is not entirely unexpected that Extended Protection breaks authentication, since this checks if the authentication was done over the same TLS channel as the connection itself, which is of course not the case in case of a loadbalancer which handles the connections to the client.
I'm not sure about the "DisableLoopbackCheck", that is a recommendation from a Microsoft KB.

**Comment by JulioQc** [comment]
Agreed!
The DisableLoopbackCheck is recommended to be removed in the KB and it's recommended to be set to 1 in another KB Microsoft referred while helping solve my issue... I'm not entirely sure what this one does exactly but I know disabling it breaks authentication intermittently.

**Comment by dirkjanm** [comment]
Closing this since it's not really an issue with the tool.
